version: '3.4'

services:

  mssql:
    hostname: msqsqlserver-docker
    restart: always
    image: mcr.microsoft.com/mssql/server:2019-latest
    user: root
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=SomeLongPasswordGoesHere3!
    # Dev note: Could be used to persist the data, We want a fresh start with every 'boot'.
    #volumes:
      #- ./data:/var/opt/mssql/data

  paymentgatewayapi:
    hostname: paymentgatewayapi
    container_name: paymentgatewayapi
    image: ${DOCKER_REGISTRY-}paymentgatewayapi
    build:
      context: .
      dockerfile: src/PaymentGateway/PaymentGatewayAPI/Dockerfile
    env_file:
     - ./build/secrets.env.dev
    depends_on:
    - mssql
    - bankemulator

  bankemulator:
    hostname: bankemulator
    container_name: bankemulator
    image: ${DOCKER_REGISTRY-}bankemulator
    build:
      context: .
      dockerfile: src/BankEmulator/BankEmulatorAPI/Dockerfile
    env_file:
     - ./build/secrets.env.dev
    depends_on:
    - mssql